import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { wrapper } from '../components/store'
import Navigation from '../components/nav'
import Artwork from '../components/artwork'
import Commander from '../components/artwork/commander'
import Footer from '../components/ui-elements/footer'
import Icon from '../components/icons/icon'
// ui elements
import FullWidthButton from '../components/ui-elements/full-width-button'
import ProjectGridBox from '../components/ui-elements/project-grid-box'
import Clock from '../components/clock'

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Matt Lipski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Clock />

      <Navigation />

      <Artwork />

      <Commander />

      <main className="main">
        <div id="projects" className={styles.projects + " " + styles.homeFullSection}>
          <div className={styles.sectionHeader}>
          <h2>Projects</h2>
          </div>
          <div className={styles.contentWrapper}>
            <ProjectGridBox imageUrl="/before-2.png" text="This Website" link="/projects/this-site" />
            <ProjectGridBox imageUrl="/odoo.png" text="Odoo" link="/projects/odoo" />
            <ProjectGridBox imageUrl="/geckota.png" text="Geckota" link="/projects/geckota" />
            {/* <ProjectGridBox imageUrl="/porsche.jpg" text="Hobby Stuff" link="/projects/this-site" />
            <ProjectGridBox imageUrl="/temp-coming-soon.png" text="Coming Soon" link="/projects/this-site" />
            <ProjectGridBox imageUrl="/temp-coming-soon.png" text="Coming Soon" link="/projects/this-site" /> */}
          </div>
        </div>
        <div className={styles.about+" "+styles.homeFullSection} id="about">
          <div className={styles.contentWrapper}>
          <div className={styles.section}>
            <p><Icon icon="cog" color="rgb(252,176,69)"/><span>Developing across the stack</span></p>
            <p><Icon icon="light-bulb" color="rgb(252,176,69)"/><span>5+ years of experience in tech</span></p>
            <p><Icon icon="code" color="rgb(252,176,69)"/><span>Node.js, React, Python and more</span></p>
            <p><Icon icon="heart" color="rgb(252,176,69)"/><span>Arrays start at 0</span></p>
          </div>
          <div className={styles.externalButtons}>
              <div className={styles.buttonColumn}>
              <FullWidthButton icon="github" link="https://github.com/PortalFl0w" text="GitHub" />
              </div>
              <div className={styles.buttonColumn}>
              <FullWidthButton icon="linkedin" link="https://www.linkedin.com/in/matt-l5543/" text="LinkedIn" />
              </div>
              <div className={styles.buttonColumn}>
              <FullWidthButton icon="mail" link="mailto:me@mattlipski.com" text="Email Me" />
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </div>
  )
}

Home.getInitialProps = wrapper.getInitialPageProps(store => ({pathname, req, res}) => {
  console.log('2. Setting up home global variables');
  store.dispatch({type: 'TIME_SPEED', payload: 1000});
  store.dispatch({type: 'MAX_TIME', payload: 86400});
  store.dispatch({type: 'TICK_RATE', payload: 1000});
});

export default Home
