import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navigation from '../components/nav'
import Artwork from '../components/artwork'
import Footer from '../components/ui-elements/footer'
import Icon from '../components/icons/icon'
// ui elements
import FullWidthButton from '../components/ui-elements/full-width-button'
import ProjectGridBox from '../components/ui-elements/project-grid-box'
import Clock from '../components/clock'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Matt Lipski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Clock />

      <Navigation />

      <Artwork />

      <main className="main">
        <div id="projects" className={styles.projects + " " + styles.homeFullSection}>
          <div className={styles.sectionHeader}>
          <h2>Projects</h2>
          </div>
          <div className={styles.contentWrapper}>
            <ProjectGridBox imageUrl="/before-2.png" text="This Website" link="/projects/this-site" />
            <ProjectGridBox imageUrl="/odoo.png" text="Odoo" link="/projects/odoo" />
            <ProjectGridBox imageUrl="/geckota.png" text="Geckota" link="/projects/geckota" />
            {/* <ProjectGridBox imageUrl="/porsche.jpg" text="Hobby Stuff" link="/projects/this-site" />
            <ProjectGridBox imageUrl="/temp-coming-soon.png" text="Coming Soon" link="/projects/this-site" />
            <ProjectGridBox imageUrl="/temp-coming-soon.png" text="Coming Soon" link="/projects/this-site" /> */}
          </div>
        </div>
        <div className={styles.about+" "+styles.homeFullSection} id="about">
          <div className={styles.contentWrapper}>
          <div className={styles.section}>
            <p><Icon icon="cog" color="rgb(252,176,69)"/>Developing across the stack</p>
            <p><Icon icon="light-bulb" color="rgb(252,176,69)"/>5+ years of experience in tech</p>
            <p><Icon icon="code" color="rgb(252,176,69)"/>Node.js, React, Python and more</p>
            <p><Icon icon="heart" color="rgb(252,176,69)"/>Arrays start at 0</p>
          </div>
          <div className={styles.section}>
              <FullWidthButton icon="github" link="https://github.com/PortalFl0w" text="GitHub" />
              <FullWidthButton icon="linkedin" link="https://www.linkedin.com/in/matt-l5543/" text="LinkedIn" />
              <FullWidthButton icon="mail" link="mailto:me@mattlipski.com" text="Email Me" />
          </div> 
          </div>
        </div>
        <Footer />
      </main>
    </div>
  )
}
